service: pricecalculator

provider:
  name: aws
  runtime: nodejs12.x

functions:
  root:
    handler: handler.hello
    memorySize: 128
    events:
      - http:
          path: /
          method: get